#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "master"
order = "asc"
unknown-type = "feature"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[hosting]
dev-remote = "origin"
forge-type = "github"
github-connector = "api"

[propose]
breadcrumb = "none"
breadcrumb-direction = "down"

[ship]
delete-tracking-branch = false
ignore-uncommitted = false
strategy = "api"

[sync]
auto-sync = false
detached = true
perennial-strategy = " rebase"
feature-strategy = "merge"
prototype-strategy = "merge"
push-branches = true
push-hook = false
tags = true
upstream = false
