#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "master"
order = "asc"
unknown-type = "prototype"
feature-regex = "^(feature|fix|ci|test|doc)\\/.+"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[hosting]
dev-remote = "origin"
forge-type = "github"
github-connector = "api"
origin-hostname = "github.com"

[propose]
breadcrumb = "none"

[ship]
delete-tracking-branch = false
ignore-uncommitted = false
strategy = "api"

[sync]
auto-resolve = true
auto-sync = true
detached = false
feature-strategy = "rebase"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-branches = true
push-hook = false
tags = true
upstream = false
