#Requires -Version 7
# pyenv help: Show pyenv help text
param()

Write-Output "pyenv $(Get-PyenvVersion)"
Write-Output "Usage: pyenv <command> [<args>]"
Write-Output ""
Write-Output "Some useful pyenv commands are:"
Write-Output "   commands     List all available pyenv commands"
Write-Output "   duplicate    Creates a duplicate python environment"
Write-Output "   export       Exports a Python version to a specified path"
Write-Output "   migrate      Migrate pip packages between Python versions"
Write-Output "   local        Set or show the local application-specific Python version"
Write-Output "   latest       Print the latest installed or known version with the given prefix"
Write-Output "   global       Set or show the global Python version"
Write-Output "   shell        Set or show the shell-specific Python version"
Write-Output "   install      Install 1 or more versions of Python"
Write-Output "   uninstall    Uninstall a specific Python version"
Write-Output "   update       Update the cached version DB"
Write-Output "   rehash       Rehash pyenv shims (run this after installing executables)"
Write-Output "   vname        Show the current Python version"
Write-Output "   version      Show the current Python version and its origin"
Write-Output "   version-name Show the current Python version"
Write-Output "   versions     List all Python versions available to pyenv"
Write-Output "   exec         Runs an executable by first preparing PATH so that the selected"
Write-Output "                Python version's directory is at the front"
Write-Output "   which        Display the full path to an executable"
Write-Output "   whence       List all Python versions that contain the given executable"
Write-Output ""
Write-Output "See ``pyenv help <command>' for information on a specific command."
Write-Output "For full documentation, see: https://github.com/satori-analytics/pyenv-win#readme"
